language: python
sudo: false
python:
  - '2.7_with_system_site_packages'
  - 3.4
  - 3.5
  - 3.6
addons:
  apt:
    packages:
    - python-qt4
    - python-qt4-dev
    - python-qt4-gl
    - python-pip
    - python-numpy
    - python-wxtools
    - ccache
    - cmake
    - swig
    - zlib1g-dev
    - libpng-dev
    - libfreetype6-dev
    - python-cairo
env:
  - ETS_TOOLKIT=wx PILLOW='pillow'
  - ETS_TOOLKIT=qt4 PILLOW='pillow'
  - ETS_TOOLKIT=null.image PILLOW='pillow<3.0.0'
  - ETS_TOOLKIT=null.image PILLOW='pillow'
matrix:
  exclude:
    - python: 3.4
      env: ETS_TOOLKIT=wx PILLOW='pillow'
    - python: 3.5
      env: ETS_TOOLKIT=wx PILLOW='pillow'
    - python: 3.5
      env: ETS_TOOLKIT=qt4 PILLOW='pillow'
    - python: 3.6
      env: ETS_TOOLKIT=wx PILLOW='pillow'
    - python: 3.6
      env: ETS_TOOLKIT=qt4 PILLOW='pillow'
cache:
  directories:
    - $HOME/.cache
    - $HOME/.ccache
before_install:
  - ccache -s
  - export PATH=/usr/lib/ccache:${PATH}
  - pip install --upgrade pip
  - if [[ ${TRAVIS_PYTHON_VERSION} == "3.4" && ${ETS_TOOLKIT} == "qt4" ]]; then ./build_pyside_wheel.sh; fi
  - if [[ ${TRAVIS_PYTHON_VERSION} == "3.5" && ${ETS_TOOLKIT} == "qt4" ]]; then ./build_pyside_wheel.sh; fi
  - if [[ ${TRAVIS_PYTHON_VERSION} == "3.6" && ${ETS_TOOLKIT} == "qt4" ]]; then ./build_pyside_wheel.sh; fi
  # setup X11 for the tests
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  # Install pillow separately to control the version
  - pip install $PILLOW
  - pip install -r travis-ci-requirements
  - python setup.py develop
before_script:
  - mkdir testrunner
  - cp .coveragerc testrunner
  - cd testrunner
script:
  - coverage run -m nose.core enable -v
  - coverage run -a -m nose.core kiva -v
after_success:
  - pip install codecov
  - codecov
