language: python
python:
  - '2.7_with_system_site_packages'
  - 2.6
env:
  - ETS_TOOLKIT=qt4
  - ETS_TOOLKIT=wx
  - ETS_TOOLKIT=null.image
matrix:
  exclude:
    - python: 2.6
      env: ETS_TOOLKIT=qt4
    - python: 2.6
      env: ETS_TOOLKIT=wx
before_install:
  - sh ./travis_setup.sh
  # setup X11 for the tests
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  # nose is already installed
  # numpy is already installed
  - pip install -r dev_requirements.txt
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install -r requirements-2.6.txt; fi
  - pip install coveralls
  - python setup.py develop
script:
  - coverage run -m nose.core -v enable/tests
  - coverage run -a -m nose.core -v enable/savage/svg/tests
  - coverage run -a -m nose.core -v kiva/tests
  - coverage run -a -m nose.core -v kiva/agg/tests
after_success:
  coveralls
